server:
  port: 80

spring:
  h2:
    console:
      enabled: true
      path: /h2-console/
  datasource:
    url: jdbc:h2:mem:todolist # h2 database 連接位址
    driver-class-name: org.h2.Driver # 配置driver
    username: sa # database 用戶名
    password:  # database 密碼

  rabbitmq:
      host: 140.136.151.74
      port: 5672
      username: guest
      password: guest

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

